const DATA = [{
        "cntntsNo": 14911,
        "contntsName": "떡갈 고무나무",
        "plntzrNm": "fiddle leaf fig",
        "light": 2,
        "humidity": 2,
        "temperature": 3,
        "size": 3,
        "managelevelCodeNm": 2,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "보통",
        "tips": "큼직하고 진한 잎 색상 때문에 중후한 멋이 있는 떡갈잎 고무나무. 강한 생명력과 멋진 모양 덕분에 인기가 많아요. 과습으로 인해 잎이 검게 변하면서 떨어질 수 있으니 주의해주시고, 여름에 물이 젖은 천으로 잎을 닦아주면 좋아요.",
        "toxctyInfo": "독성 있을 수 있음(반려동물_아이_조심)",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실, 발코니"
    },
    {
        "cntntsNo": 13210,
        "contntsName": "녹영(콩선인장)",
        "plntzrNm": "String of Pearls,String-of-Beads",
        "light": 2,
        "humidity": 2,
        "temperature": 3,
        "size": 2,
        "managelevelCodeNm": 3,
        "watercycleSprngCodeNm": "흙이 많이 말랐을 때 넉넉히 주세요",
        "managedemanddoCodeNm": "보통",
        "tips": "행잉플랜트(걸이용 식물)로 인기가 많아요. 건조에 강한 식물이니 겉흙이 완전히 마르면 물을 주세요.  사계절 피는 작고 하얀 꽃이 파란 콩 모양의 잎과 어우러져 귀엽답니다. 온도가 낮은 환경에서는 특별히 흙을 건조하게 관리하여야 해요.",
        "toxctyInfo": "독성 있을 수 있음(반려동물_아이_조심)",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실, 발코니"
    },
    {
        "cntntsNo": 12974,
        "contntsName": "군자란",
        "plntzrNm": "Scarlet Caffir Lily,Kaffir Lily, Clivia, Bus",
        "light": 2,
        "humidity": 2,
        "temperature": 2,
        "size": 2,
        "managelevelCodeNm": 3,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "보통",
        "tips": "군자란의 수명은 30년 이상으로 장수하는 식물이에요.",
        "toxctyInfo": "독성 있을 수 있음(반려동물_아이_조심)",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실, 발코니"
    },
    {
        "cntntsNo": 13186,
        "contntsName": "금전수(돈나무)",
        "plntzrNm": "Eternity Plant, Fat Boy,Aroid Palm",
        "light": 2,
        "humidity": 2,
        "temperature": 3,
        "size": 2,
        "managelevelCodeNm": 2,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "강함",
        "tips": " 광택이 있는 잎이 매력적이에요. 그늘진 곳에서 잘 견디지만, 실내 밝은 간접광을 더 좋아해요.\n환경 조건에 견디는 힘이 뛰어나고 과습이 되면 뿌리가 썩기 쉬우니 주의해주세요.",
        "toxctyInfo": "독성 있을 수 있음(반려동물_아이_조심)",
        "frtlzrInfo": "비료_가끔",
        "postngplaceCodeNm": "거실"
    },
    {
        "cntntsNo": 12963,
        "contntsName": "관음죽",
        "plntzrNm": "Fan Palms, (Large) Lady Palm, Bamboo Palm",
        "light": 2,
        "humidity": 2,
        "temperature": 2,
        "size": 3,
        "managelevelCodeNm": 3,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "보통",
        "tips": "집에서 기르기 쉽고, 그늘과 추위에도 잘 견디고 병해충에도 강하답니다. 자라는 속도가 느려서 관리도 편하고요. 수경재배로 기르는 경우에는 수돗물 속의 염분이나 미네랄이 잎 끝에 축적되어 갈색으로 변할 수 있는데,  갈색으로 변한 부분만 가위로 잘라내어 주세요. 염분도 제거할 수 있고 특유의 톱니모양의 녹색 잎을 유지시킬 수 있어요.  2년에 한 번씩 분갈이를 해 주면 좋아요.",
        "toxctyInfo": "독성 있을 수 있음(반려동물_아이_조심)",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "약간 어두운 곳"
    },
    {
        "cntntsNo": 16449,
        "contntsName": "몬스테라",
        "plntzrNm": "monstera",
        "light": 2,
        "humidity": 3,
        "temperature": 3,
        "size": 3,
        "managelevelCodeNm": 2,
        "watercycleSprngCodeNm": "흙을 항상 촉촉하게 유지해주세요",
        "managedemanddoCodeNm": "보통",
        "tips": "몬스테라는 덩굴성 대형관엽식물로 6~8m 까지 자라요. 잎이 진녹색으로 크고 광택이 나며 잎맥 사이에 군데군데 타원형의 구멍이 파여 있어 폭우나 강한 바람에도 견딜 수 있는 구조로 발달했어요. 흰색의 꽃이 피고 열매도 달려요.  그리고 빗물을 주면 토양이 산성화 될 수도 있어요. 따뜻한 물을 사용해주세요. 더운 여름에는 물 젖은 천으로 잎을 닦아 주고, 분무해주세요. \n직시광선에 노출시키면 잎이 타기 쉬우므로 그늘에 놓아주세요.",
        "toxctyInfo": "독성 있을 수 있음(반려동물_아이_조심)",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실, 발코니"
    },
    {
        "cntntsNo": 14918,
        "contntsName": "칼라데아 인시그니스",
        "plntzrNm": "rattle snake plant",
        "light": 2,
        "humidity": 2,
        "temperature": 3,
        "size": 2,
        "managelevelCodeNm": 3,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "보통",
        "tips": "잎의 무늬가 선명하여 실내 인테리어 포인트로 좋아요. 어두운 곳에 오래 있으면 잎 끝이 아래로 처지거나 싹 끝이 시드는 등의 증상이 있을 수 있어요. 또 건조할 경우에는 잎이 말리는 현상이 있으므로 직사광선을 피해주세요. ",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실, 발코니"
    },
    {
        "cntntsNo": 14697,
        "contntsName": "드라세나 콤팩타",
        "plntzrNm": "calypso queen, dwarf bouquet, dracaena compa",
        "light": 2,
        "humidity": 2,
        "temperature": 3,
        "size": 3,
        "managelevelCodeNm": 2,
        "watercycleSprngCodeNm": "흙을 항상 촉촉하게 유지해주세요",
        "managedemanddoCodeNm": "보통",
        "tips": "집안에서 키우기 아주 좋은 식물이며, 공기정화능력(포름알데히드, 벤젠, 톨루엔 등 제거)이 뛰어나요. 잎은 짙은 암녹색이고 광택이 나며 줄기에서 나선형으로 촘촘하게 돌려서 나와요. 옥수수자루 같은 넓은 잎들이 방사형으로 무성하게 달리고 기왓장을 쌓듯 층층으로 성장해요.\n 수분은 약간 축축해도 상관없지만 과습할 경우 잎이 가늘고 거칠어진답니다. 여름철에는 직사광선을 반드시 피해야 해요.  \n고온다습한 장마철 겨울은 물주기를 줄이고, 건조한 것을 싫어하는 식물이기 때문에 겨울에는 분무기로 한 번씩 물을 뿌려 주는 것이 좋아요.  밭흙, 부엽, 모래를 3:5:2의 비율로 혼합하고, 4~9월에 월 1회 복합비료를 주시면 좋아요. ",
        "toxctyInfo": "독성 있을 수 있음(반려동물_아이_조심)",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "약간 어두운 곳"
    },
    {
        "cntntsNo": 14688,
        "contntsName": "드라세나 드라코",
        "plntzrNm": "dragon tree",
        "light": 2,
        "humidity": 2,
        "temperature": 3,
        "size": 3,
        "managelevelCodeNm": 3,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "보통",
        "tips": "이국적인 느낌의 관상가치가 높은 식물이에요. 자연에서는 아주 큰 나무이지만 실내에서는  1m까지만 자라요.  줄기나 잎을 자르면 그 단면에 붉은 액체가 흐른다고 해서 ‘용혈수’(龍血樹)라고도 불려요. 물은 따뜻한 물로 주세요. 빛이 충분하면 잎 가장자리에 약간 붉은색 띄게 돼요. 오래된 잎은 아래쪽으로 아치형을 그리고요. 산소와 음이온을 많이 내뿜어 공기정화 효과가 뛰어나답니다. ",
        "toxctyInfo": "독성 있을 수 있음(반려동물_아이_조심)",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실"
    },
    {
        "cntntsNo": 14690,
        "contntsName": "행운목",
        "plntzrNm": "corn plant",
        "light": 2,
        "humidity": 2,
        "temperature": 3,
        "size": 3,
        "managelevelCodeNm": 2,
        "watercycleSprngCodeNm": "흙을 항상 촉촉하게 유지해주세요",
        "managedemanddoCodeNm": "강함",
        "tips": "사무실이나 실내 장식이 많은 매장, 거실에 두면 보기에도 좋고 실내의 답답함을 없애, 공간을 시원하게 연출할 수 있어요.\n 반그늘에서 잘 자라고 추위에도 강해요. 잎의 폭은 넓고 끝이 뾰족하며 늘어지는데 마치 옥수수 잎을 연상시키는 식물이에요.  실내에서는 3m까지 생장하는데, 줄기 윗부분을 20cm 정도 잘라주면 새로운 싹이 나와 자라고, 원기회복에 큰 도움이 된답니다. 오래된 나무인 경우는 봄과 여름동안 비료의 양을 늘려주세요.",
        "toxctyInfo": "독성 있을 수 있음(반려동물_아이_조심)",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실"
    },
    {
        "cntntsNo": 14913,
        "contntsName": "러브체인",
        "plntzrNm": "rosary vine, string of hearts",
        "light": 2,
        "humidity": 2,
        "temperature": 2,
        "size": 2,
        "managelevelCodeNm": 3,
        "watercycleSprngCodeNm": "흙이 많이 말랐을 때 넉넉히 주세요",
        "managedemanddoCodeNm": "보통",
        "tips": "행잉플랜트(걸이용 식물)로 적합해요.  폭포처럼 아래쪽으로 길게 늘어지는 특성이 있어 거실이나 베란다에 걸어두기 좋아요. 비료를 자주 주어야 길게 늘어지며 자랍니다.줄기는 1~3m까지 자라며, 잎 앞면에 회백색 그물 무늬가 있고 뒷면은 적자색이다. 다른 덩굴식물과는 달리 땅속줄기에 덩이뿌리(물 저장뿌리)가 있어 다습한 환경을 싫어하고, 건조에 강해요.\n 규칙적인 환기가 필요해요. 과습과 과한 물주기는 피해주시고 따뜻한 물을 사용하세요. 여름철에 1~2cm 분홍색 깔때기 모양으로 생긴 독특한 꽃이 피고 꽃이 피는 기간은 긴 편이에요.\n 번식은 줄기 삽목을 주로 이용하는데, 덩굴을 두세 마디씩 잘라서 땅에 꽂거나 덩굴에 생기는 작은 덩이를 묻어두면 싹이 난답니다.",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_가끔",
        "postngplaceCodeNm": "거실, 발코니"
    },
    {
        "cntntsNo": 18601,
        "contntsName": "에크메아 파시아타",
        "plntzrNm": "urn plant, silver vase",
        "light": 2,
        "humidity": 2,
        "temperature": 3,
        "size": 2,
        "managelevelCodeNm": 3,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "보통",
        "tips": "색깔이 선명한 포엽(잎이 꽃모양으로 변형된 것)이 아름답고, 관상기간이 길어요.",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실, 발코니"
    },
    {
        "cntntsNo": 14689,
        "contntsName": "드라세나 마지나타",
        "plntzrNm": "Madagascar dragon tree, red edged Dracaena",
        "light": 2,
        "humidity": 2,
        "temperature": 2,
        "size": 3,
        "managelevelCodeNm": 2,
        "watercycleSprngCodeNm": "흙을 항상 촉촉하게 유지해주세요",
        "managedemanddoCodeNm": "보통",
        "tips": "드라세나 마지나타는 잎 모양이 창처럼 가느다랗고 잎 길이는 60cm 정도예요. 특히 야자수 잎처럼 뭉쳐나는 아름다운 잎들이 우아하죠.\n실내 독성물질(자일렌과 트리클로로에틸렌 등) 제거 능력이 우수해 공기청정기 역할을 톡톡히 해내므로 실내공기 정화에 좋답니다. 뿌리가 화분구멍으로 나오는 경우 흙이 굳어져서 물 흡수가 제대로 되지 않는 경우나, 뿌리가 썩어 식물 아랫부분 잎이 시드는 경우, 분갈이를 해주는 것이 좋아요. (봄 4~6월, 겨울은 9~10월 사이) 찬물은 싫어해요.",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실"
    },
    {
        "cntntsNo": 14663,
        "contntsName": "동백나무",
        "plntzrNm": "common camellia",
        "light": 3,
        "humidity": 2,
        "temperature": 1,
        "size": 3,
        "managelevelCodeNm": 3,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "보통",
        "tips": "겨울철 바람으로 인한 탈수피해가 있을 수 있으니 조심해주세요.\n동백은 남부지방과 제주도에 자생하는 식물로, 꽃은 12~4월에 피어서 가을에 결실을 맺어요.\n 꽃의 열매는 지름 3~5mm로 붉은색이 돌며 9월에 성숙하고, “산다화“라\n 하며 약용으로도 이용돼요.",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_많이",
        "postngplaceCodeNm": "거실, 발코니"
    },
    {
        "cntntsNo": 16245,
        "contntsName": "멕시코소철",
        "plntzrNm": "sago palm",
        "light": 2,
        "humidity": 2,
        "temperature": 2,
        "size": 3,
        "managelevelCodeNm": 2,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "강함",
        "tips": "강한 빛과 그늘 모두 잘 적응하여 성장하는 식물이에요. 잎은 골판지처럼 딱딱해서 이국적인 이미지가 있어요. 잎은 1년에 한번씩 새로 자라나며, 줄기의 끝이 굵은 것 일수도록 많이 나오고, 새로 나온 잎이 완전히 굳어질 때까지 먼저 잎을 자르지 않는 것이 좋아요. ",
        "toxctyInfo": "독성 있을 수 있음(반려동물_아이_조심)",
        "frtlzrInfo": "비료_가끔",
        "postngplaceCodeNm": "거실, 발코니"
    },
    {
        "cntntsNo": 12954,
        "contntsName": "개운죽",
        "plntzrNm": "Sander's dracaena",
        "light": 2,
        "humidity": 2,
        "temperature": 3,
        "size": 3,
        "managelevelCodeNm": 2,
        "watercycleSprngCodeNm": "흙을 항상 촉촉하게 유지해주세요",
        "managedemanddoCodeNm": "강함",
        "tips": "수경은 물주기가 필요 없지만, 화분은 1-2주에 한번씩 충분히 물을 주세요. 화분에 심을 경우에는 부드럽고 배수가 잘 되는 토양에 심어 주시고요.",
        "toxctyInfo": "독성 있을 수 있음(반려동물_아이_조심)",
        "frtlzrInfo": "비료_가끔",
        "postngplaceCodeNm": "거실"
    },
    {
        "cntntsNo": 13206,
        "contntsName": "남천",
        "plntzrNm": "Heavenly bamboo, Sacred Bamboo ",
        "light": 3,
        "humidity": 2,
        "temperature": 2,
        "size": 3,
        "managelevelCodeNm": 2,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "강함",
        "tips": "흙의 물빠짐이 좋아야 하고 지나친 과습과 건조는 잎을 황화시켜 떨어지게 해요. 꽃, 열매, 잎, 단풍이 모두 아름답고 실내의 동양적인 분위기에 잘 어울린다.\n 남천의 열매를 남천실이라 하며 해수, 천식, 백일해, 간기능장애 등에 약제로 사용한다.",
        "toxctyInfo": "독성 있을 수 있음(반려동물_아이_조심)",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실, 발코니"
    },
    {
        "cntntsNo": 19663,
        "contntsName": "세이브릿지 야자",
        "plntzrNm": "reed palm",
        "light": 2,
        "humidity": 2,
        "temperature": 3,
        "size": 3,
        "managelevelCodeNm": 2,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "보통",
        "tips": "최대 2m 정도 자라며 모양이 가늘고 호리호리한 줄기들이 모여 하나의 다발을 이루는 형태를 가져요. 주황빛을 띄는 줄기에 검은색의 열매가 맺히지만 독성이 있으므로 먹으면 안 돼요! 생장이 매우 빠른편으로 반양지에서 직사광선을 피하여 기르는 것이 좋고 광량이 너무 적으면 잎이 전체적으로 처지고 모양이 흐트러질 수 있어요. 물은 화분구멍으로 흘러나올 만큼 흠뻑 주며 하루에 한 두 차례 스프레이로 뿌려 줄 경우 수형을 유지하는데 도움이 돼요. 1989년 나사에서 발표한 50종의 우수실내정화식물 중 하나로 증산작용이 뛰어나고 휘발성 화학물질 제거 능력이 매우 우수하여 공기 정화식물로 인기가 높아요.",
        "toxctyInfo": "독성 있을 수 있음(반려동물_아이_조심)",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "발코니"
    },
    {
        "cntntsNo": 13248,
        "contntsName": "파키라",
        "plntzrNm": "guiana chestnut,malaba chestnut, provision t",
        "light": 2,
        "humidity": 2,
        "temperature": 3,
        "size": 3,
        "managelevelCodeNm": 3,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "보통",
        "tips": "외국에서는 Money tree라고 불리우고, 잎과 꽃은 채소처럼 식용하고, 열매는 땅콩맛이 나요.",
        "toxctyInfo": "해독작용",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실"
    },
    {
        "cntntsNo": 13319,
        "contntsName": "칼랑코에",
        "plntzrNm": "kalanchoe, flaming katy",
        "light": 2,
        "humidity": 2,
        "temperature": 3,
        "size": 2,
        "managelevelCodeNm": 2,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "보통",
        "tips": "누구나 쉽게 키울 수 있어요.",
        "toxctyInfo": "독성 있을 수 있음(반려동물_아이_조심)",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실, 발코니"
    },
    {
        "cntntsNo": 19706,
        "contntsName": "수박페페",
        "plntzrNm": "watermelon peperomia, watermelon begonia",
        "light": 2,
        "humidity": 2,
        "temperature": 3,
        "size": 2,
        "managelevelCodeNm": 3,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "보통",
        "tips": "새집증후군 원인물질인 자일렌, 포름알데히드을 제거해주는 우수한 공기정화식물이에요. 빛을 너무 적게 받으면 웃자라고 실내에서 재배할 때 습도 40~70%를 유지해주셔야 해요. 추위에 약해 겨울철 온도관리에 주의하고 부엽토성분의 배수가 잘되는 토양에 심어주세요. 깍지벌레 응애와 같은 병충해에 주의해야 해요.",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실, 발코니"
    },
    {
        "cntntsNo": 19716,
        "contntsName": "스킨답서스",
        "plntzrNm": "scindapsus, devils ivy, goden pothos, hunter",
        "light": 2,
        "humidity": 2,
        "temperature": 3,
        "size": 2,
        "managelevelCodeNm": 2,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "보통",
        "tips": "관리가 쉽고 잘 자라는 식물로 병해충에 대한 강한 저항성을 갖고 있어요. 실내관엽 식물중 일산화탄소 제거능력이 우수하고 어두운 곳에서도 잘 적응해요. 약 40m 길이까지 자랄 수 있는 덩굴성으로 행잉플랜트로도 활용해요. 여러무늬 종들이 있으며 공기 정화력도 가지고 있어요. 단, 칼슘옥살레이트 성분을 가지고 있어 애완동물에게는 독성이 있으니 조심하세요. 수경재배도 가능해요. 반음지에서 잘 자라며 겨울철에는 충분히 빛을 받게 하면서 물은 적게 주세요.",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "약간 어두운 곳"
    },
    {
        "cntntsNo": 18691,
        "contntsName": "아프리칸 바이올렛",
        "plntzrNm": "african violet",
        "light": 2,
        "humidity": 2,
        "temperature": 3,
        "size": 2,
        "managelevelCodeNm": 3,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "보통",
        "tips": "다년생, 다육질의 타원형 잎에 털이 있고, 꽃의 색상과 형태에 따라 아주 다양한 품종이 있어요. 잎의 털에 물방울이 고여 있으면 곰팡이병이 생길 수 있고, 진한 꽃잎에 물방울이 묻어 물방울이 데워짐으로 꽃 색이 바래질 수 있어요. 물을 줄때 저면관수 방법이나, 흙으로만 물이 주어지도록 주의해주세요. ",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실, 발코니"
    },
    {
        "cntntsNo": 18659,
        "contntsName": "박쥐란",
        "plntzrNm": "common staghorn fern, elkhorns",
        "light": 2,
        "humidity": 2,
        "temperature": 3,
        "size": 2,
        "managelevelCodeNm": 4,
        "watercycleSprngCodeNm": "흙을 항상 촉촉하게 유지해주세요",
        "managedemanddoCodeNm": "보통",
        "tips": "원산지는 열대 아프리카, 열대 아시아, 온대 오스트레일리아로 14종이나 있어요. 잎 표면은 회녹색이고 뒷면은 녹백색이에요. 회녹색의 사슴뿔 모양을 지니고 있으며 밝은 곳을 좋아해요. 건조한 것 보다는 습한 환경을 좋아하므로 잎에 자주 분무해주세요.",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실, 발코니"
    },
    {
        "cntntsNo": 19451,
        "contntsName": "산호수",
        "plntzrNm": "Small coralberry",
        "light": 2,
        "humidity": 2,
        "temperature": 2,
        "size": 2,
        "managelevelCodeNm": 2,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "강함",
        "tips": "꽃, 열매, 잎 모두 다 관상가치가 있으며 키우기 쉬운 관엽 식물이에요. 추위에 약해 중부지방 위로는 실외 월동이 어려워요. 반 그늘진 곳을 좋아하며 어느 정도 습기유지가 중요해요. 씨앗을 12-4월에 따서 과육을 제거하고 뿌리거나 봄 또는 여름에 줄기를 삽목하면 잘 번식해요. ",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실"
    },
    {
        "cntntsNo": 19707,
        "contntsName": "시클라멘",
        "plntzrNm": "Cyclamen",
        "light": 2,
        "humidity": 2,
        "temperature": 3,
        "size": 2,
        "managelevelCodeNm": 4,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "보통",
        "tips": "꽃은 11월~3월까지 피고, 한줄기 끝에 1개의 꽃이 피며, 보라색, 분홍색, 빨강색, 흰색 등 꽃 색이 다양해요. 통풍이 잘 되는 서늘한 곳을 좋아해요. 하트모양의 독특한 화형을 오랫동안 감상 할 수 있고 겨울철 실내에서 재배가 용이한 장점이 있어요. 관수는 잎과 구근이 닿지 않도록 저면관수 하는 것이 좋아요. 생육온도는 16~20℃로 여름철 차광을 해서 온도조절을 해주세요. 진딧물, 응애, 온실가루이 등 병충해에 조심하시고요.",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실, 발코니"
    },
    {
        "cntntsNo": 19714,
        "contntsName": "싱고니움",
        "plntzrNm": "Goose foot",
        "light": 2,
        "humidity": 2,
        "temperature": 2,
        "size": 2,
        "managelevelCodeNm": 3,
        "watercycleSprngCodeNm": "흙을 항상 촉촉하게 유지해주세요",
        "managedemanddoCodeNm": "보통",
        "tips": "연두색, 흰색, 빨강, 분홍색등의 잎색과 줄무늬, 점무늬 등 다양한 잎모양을 지닌 대표적인 잎보기식물이에요. 실내 암모니아 제거능력 우수하고 반그늘을 좋아하며 고온다습한 환경에서 잘 자라요. 응애, 깍지벌레, 온실가루이 병충해를 조심한다.",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실, 발코니"
    },
    {
        "cntntsNo": 19461,
        "contntsName": "아이비",
        "plntzrNm": "english ivy, baltic ivy",
        "light": 2,
        "humidity": 2,
        "temperature": 2,
        "size": 2,
        "managelevelCodeNm": 2,
        "watercycleSprngCodeNm": "흙을 항상 촉촉하게 유지해주세요",
        "managedemanddoCodeNm": "강함",
        "tips": "아이비는 더운 것을 싫어하므로 너무 더운 곳은 피하고 조금 서늘한 곳에서 키우는 것이 좋아요. 주위가 건조할 때는 잎에 자주 분무해주세요.",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실"
    },
    {
        "cntntsNo": 13004,
        "contntsName": "틸란드시아",
        "plntzrNm": "blue-flowered torch, pink quill",
        "light": 2,
        "humidity": 2,
        "temperature": 2,
        "size": 2,
        "managelevelCodeNm": 3,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "보통",
        "tips": "분홍색의 화포에서 남보라색 꽃이 차례로 피는데 같은 포에서 3~4장의 꽃잎이 펴요. 행잉플랜트로 인기가 좋아요.",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실, 발코니"
    },
    {
        "cntntsNo": 13245,
        "contntsName": "팔레놉시스(호접란)",
        "plntzrNm": "Phalaenopsis",
        "light": 2,
        "humidity": 2,
        "temperature": 3,
        "size": 2,
        "managelevelCodeNm": 4,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "특별 관리 필요",
        "tips": "실내공기가 너무 건조하면 개각충이나 응애가 발생하니 주의해주세요.",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실"
    },
    {
        "cntntsNo": 16037,
        "contntsName": "보스톤고사리",
        "plntzrNm": "Boston fern",
        "light": 2,
        "humidity": 3,
        "temperature": 3,
        "size": 2,
        "managelevelCodeNm": 2,
        "watercycleSprngCodeNm": "흙을 항상 촉촉하게 유지해주세요",
        "managedemanddoCodeNm": "보통",
        "tips": "한여름의 직사광선은 피하고 습도유지가 되어야 잘 자라요. 풍성하고 아름다운 잎 때문에 빅토리아 시대부터 실내에 도입되어 사랑을 받아왔으며, 오늘날에도 여전히 인기가 높은 실내식물이에요. 유기질이 풍부한 화분용 배합토에서 잘 자라고, 뿌리가 화분 가득히 뻗어있는 것이 좋아요.",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실"
    },
    {
        "cntntsNo": 13338,
        "contntsName": "덴파레",
        "plntzrNm": "Cocktown orchid",
        "light": 3,
        "humidity": 2,
        "temperature": 3,
        "size": 2,
        "managelevelCodeNm": 3,
        "watercycleSprngCodeNm": "흙이 많이 말랐을 때 넉넉히 주세요",
        "managedemanddoCodeNm": "보통",
        "tips": "봄-가을 까지는 실외에 두고 꽃이 개화하여 80%정도에서 꽃대를 잘라주면 새로운 싹을 받기에 좋아요.",
        "toxctyInfo": "",
        "frtlzrInfo": "",
        "postngplaceCodeNm": "거실, 발코니"
    },
    {
        "cntntsNo": 19711,
        "contntsName": "수염 틸란드시아",
        "plntzrNm": "spanish moss",
        "light": 2,
        "humidity": 3,
        "temperature": 3,
        "size": 2,
        "managelevelCodeNm": 3,
        "watercycleSprngCodeNm": "분무기로 물 자주",
        "managedemanddoCodeNm": "보통",
        "tips": "뿌리가 없이 공중에서 습도와 영양분을 흡수하므로 건조하지 않도록 자주 분무해주세요. 먼지먹는 식물로도 알려져 있어요.",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_가끔",
        "postngplaceCodeNm": "거실"
    },
    {
        "cntntsNo": 19712,
        "contntsName": "심비디움",
        "plntzrNm": "Cymbidium Orchid, boat orchids",
        "light": 2,
        "humidity": 3,
        "temperature": 2,
        "size": 2,
        "managelevelCodeNm": 4,
        "watercycleSprngCodeNm": "흙이 많이 말랐을 때 넉넉히 주세요",
        "managedemanddoCodeNm": "보통",
        "tips": "‘물위의 배’라는 뜻으로 꽃은 2개의 꽃잎 1개의 설판, 3개의 꽃받침으로 구성돼요. 분홍색, 빨강색, 노란색, 흰색 등 다양한 색을 갖고 있으며 화려하지만 대부분 향기가 없어요. 우리나라에서는 겨울철에 꽃이 피어요. 과습에 약하므로 건조하게 관리해주세요. 뿌리가 꽉 차기 전, 3~4월에 분갈이를 하는 것이 좋아요.",
        "toxctyInfo": "",
        "frtlzrInfo": "",
        "postngplaceCodeNm": "발코니"
    },
    {
        "cntntsNo": 18578,
        "contntsName": "익소라",
        "plntzrNm": "broken pot, prince of orange",
        "light": 2,
        "humidity": 2,
        "temperature": 3,
        "size": 2,
        "managelevelCodeNm": 3,
        "watercycleSprngCodeNm": "흙을 항상 촉촉하게 유지해주세요",
        "managedemanddoCodeNm": "보통",
        "tips": "꽃이 피어 있는 시간이 길고 짙은 녹색의 잎이 매혹적으로 빛나서 인기 있는 상록저목이에요. 또한 꽃이 피어도 열매는 맺지 않는 것이 특징이에요.",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실, 발코니"
    },
    {
        "cntntsNo": 16248,
        "contntsName": "제라니움",
        "plntzrNm": "geranium, fish geranium",
        "light": 2,
        "humidity": 2,
        "temperature": 2,
        "size": 2,
        "managelevelCodeNm": 2,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "강함",
        "tips": "겉흙이 마르기 시작하면 물을 충분히 주세요.",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실, 발코니"
    },
    {
        "cntntsNo": 18660,
        "contntsName": "안스리움",
        "plntzrNm": "common anthurium, flamingo flower, oilcloth ",
        "light": 2,
        "humidity": 2,
        "temperature": 3,
        "size": 2,
        "managelevelCodeNm": 3,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "보통",
        "tips": "오랫동안 감상 할 수 있는 광택이 있는 포엽이 아름다워 실내에서 분화로 기르는 열대 관엽 관화 식물이에요.일산화탄소, 암모니아 가스 제거 능력이 좋기 때문에 주방이나 화장실에 두기 좋아요. 여름철 직사광선을 피하고, 겨울철 밝은 빛을 유지해줘야 해요. 습한 것을 좋아해 자주 분무 해주는 것이 좋아요.",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실, 발코니"
    },
    {
        "cntntsNo": 19448,
        "contntsName": "산세베리아",
        "plntzrNm": "mother in law's tongue, snake plant",
        "light": 2,
        "humidity": 2,
        "temperature": 3,
        "size": 2,
        "managelevelCodeNm": 2,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "강함",
        "tips": "산세베리아는 이탈리아 산 세베로의 왕자 라이문도 디 산그로(Raimondo di Sangro, 1710~1771)를 기리기 위해 붙인 이름이에요.  이 식물의 영어 이름이 ‘시어머니의 혀’인 것은 꼿꼿하게 자라면서 가죽처럼 잎이 질기기 때문에 붙여졌다고 해요. 공기정화식물로 인기가 있어요. 실내에서 꽃 피기는 상당히 어렵지만, 환경이 좋으면 흰빛에 가까운 옅은 그린색의 작은 꽃들이 피기도 해요. 품종은 여러 종류가 있지만 가장자리에 노란 테두리가 있는 종이 가장 보편적이에요. 개나 고양이와 같은 애완동물이 섭취했을 경우는 구토나 설사를 일으킬 수 있으므로 조심해야 해요. 과습하지 않더라도 실내 온도가 10℃ 이하인 경우 썩는 원인이 될 수 있어요.",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_가끔",
        "postngplaceCodeNm": "약간 어두운 곳"
    },
    {
        "cntntsNo": 12955,
        "contntsName": "율마(골드크레스트)",
        "plntzrNm": "Monterey cypress",
        "light": 3,
        "humidity": 2,
        "temperature": 2,
        "size": 3,
        "managelevelCodeNm": 3,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "보통",
        "tips": " 바람에 약하며 줄기 아랫부분의 잎이 떨어지면 황량한 느낌을 주지만 토피아리 형식으로 키울 수도 있어요. 크리스마스 트리로 실내에 장식해도 잘 어울려요. 겨울에는 건조하게 관리해주세요. 어린 나무일수록 물을 더 자주 주세요.",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실, 발코니"
    },
    {
        "cntntsNo": 13260,
        "contntsName": "크로톤",
        "plntzrNm": "garden croton, variegated croton",
        "light": 2,
        "humidity": 2,
        "temperature": 3,
        "size": 3,
        "managelevelCodeNm": 3,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "보통",
        "tips": "열대성 상록 관목으로 다양한 잎 모양과 잎색에 따른 품종이 많고 빛에 대한 적응성이 강해서 어두운 곳에서도 오래 견뎌요. 온도에 대해서는 민감하게 반응해서 저온조건에서는 잎이 잘 떨어져요. 매년 봄에 분을 갈아주세요. ",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실, 발코니"
    },
    {
        "cntntsNo": 13214,
        "contntsName": "포인세티아",
        "plntzrNm": "poinsettia, christmas flower, painted leaf, ",
        "light": 3,
        "humidity": 2,
        "temperature": 3,
        "size": 3,
        "managelevelCodeNm": 3,
        "watercycleSprngCodeNm": "흙을 항상 촉촉하게 유지해주세요",
        "managedemanddoCodeNm": "보통",
        "tips": "추위에 약한 식물로 온도가 낮으면 잎이 떨어져요. 잎에서 나오는 흰색 즙액은 피부나 눈에 염증을 일으킬 수 있으므로 조심하세요.",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실, 발코니"
    },
    {
        "cntntsNo": 16246,
        "contntsName": "멜라니 고무나무",
        "plntzrNm": "Robust Rubbertree, Rubber Plant, Rubbertree",
        "light": 2,
        "humidity": 2,
        "temperature": 3,
        "size": 3,
        "managelevelCodeNm": 3,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "보통",
        "tips": "라텍스를 포함하고 있는 가죽질감의 짙은 녹색을 띤 뚜꺼운 잎을 가지고 있으며, 2,5m까지 자랄 수 있어요. 야생에서는 커다란 교목으로 자라는 고무나무로 잎 모양은 크고 넓은 둥근 타원형으로 엽육이 두껍고 생육이 왕성해요. 음이온과 산소발생량이 많은 식물이에요. 새로 나오는 잎은 색이 붉은빛이나 차츰 성장하며 짙은 녹색으로 바뀌는 아름다운 품종이에요. 차가운 물을 주지 않도록 주의해주세요. 더운 여름에는 물 젖은 천으로 잎을 닦아주세요. ",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실, 발코니"
    },
    {
        "cntntsNo": 14919,
        "contntsName": "벤자민고무나무",
        "plntzrNm": "Weeping Fig",
        "light": 2,
        "humidity": 2,
        "temperature": 3,
        "size": 3,
        "managelevelCodeNm": 3,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "보통",
        "tips": "상록 교목, 실내 대형 화분, 줄기가 유연하여 자유롭게 구부러져요. 환경에 빨리 적응하지 못하므로 갑자기 햇빛으로 내 놓거나, 햇빛에 있다가 실내로 옮기게 되면 잎을 많이 떨구면서 힘든 기간을 보낼 수 있어요. 서서히 적응기간을 주면서 옮기는 것이 좋아요.",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실, 발코니"
    },
    {
        "cntntsNo": 19701,
        "contntsName": "소철",
        "plntzrNm": "cycad, sago cycas, sago palm, Japanese fern ",
        "light": 2,
        "humidity": 2,
        "temperature": 2,
        "size": 3,
        "managelevelCodeNm": 2,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "강함",
        "tips": "뜰에서 재배가능한 제주도를 제외한 나머지 지역에서는 온실이나 집안에서 가꾸는 관상수예요. 꽃은 노란빛을 띤 색으로 6~8월에 암수딴그루로 펴요. 수꽃차례는 원줄기 끝에 원기둥 모양으로 달리며, 길이 50~60cm, 지름 5~8cm이고, 암꽃차례는 원줄기에 끝에 둥글게 모여 달린다. 열매는 구과로 10월에 익는데 관상용, 식용, 약용으로도 쓰여요.",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실"
    },
    {
        "cntntsNo": 13244,
        "contntsName": "팔손이나무",
        "plntzrNm": "japanese fatsia, formosa rice tree, paper pl",
        "light": 2,
        "humidity": 2,
        "temperature": 2,
        "size": 3,
        "managelevelCodeNm": 2,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "강함",
        "tips": "마치 손가락처럼 7~11열로 깊게 갈라진 큰 잎이 자라며, 잎 양면에 털이 없고 짙은 녹색으로 광택이 있고 뒷면은 황록색이에요. 4~9월까지 년 1회 영양관리 권장해요.",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실"
    },
    {
        "cntntsNo": 13213,
        "contntsName": "폴리시아스",
        "plntzrNm": "dinner plate aralia, balfour aralia",
        "light": 2,
        "humidity": 2,
        "temperature": 3,
        "size": 3,
        "managelevelCodeNm": 3,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "보통",
        "tips": "풍성하고 섬세한 잎과 부드럽게 늘어뜨려진 가지의 매력으로 실내 식물로 인기가 많아요.",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "거실"
    },
    {
        "cntntsNo": 19465,
        "contntsName": "아레카야자",
        "plntzrNm": "areca palm, butterfly palm, golden feather p",
        "light": 2,
        "humidity": 2,
        "temperature": 3,
        "size": 3,
        "managelevelCodeNm": 3,
        "watercycleSprngCodeNm": "흙 표면이 말랐을 때 넉넉히 물주기",
        "managedemanddoCodeNm": "보통",
        "tips": "NASA가 지정한 실내공기 정화 식물 중에서 가장 일등공신으로 꼽히는 식물이에요. 거실이나 사무실 등의 공기정화에 적합해요. 비교적 키우기 쉽지만 너무 강한 직사광선이나 건조한 공기는 싫어해요. 야자류 중에서는 질감도 부드럽고 부드러운 느낌을 주며 가습기를 대신할 정도로 증산량이 뛰어난 식물이에요. 일부 가지에만 염분을 축적하는 독특한 성질을 가지고 있고, 축적된 염분이 포화상태에 이르렀을 때 그 가지가 말라죽게 되므로 이때는 빨리 가지를 잘라주세요. ",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_많이",
        "postngplaceCodeNm": "거실, 발코니"
    },
    {
        "cntntsNo": 13002,
        "contntsName": "테이블야자",
        "plntzrNm": "parlour palm, good luck palm, neanthe bella",
        "light": 2,
        "humidity": 2,
        "temperature": 3,
        "size": 3,
        "managelevelCodeNm": 2,
        "watercycleSprngCodeNm": "흙을 항상 촉촉하게 유지해주세요",
        "managedemanddoCodeNm": "보통",
        "tips": "공기중에 수분을 방출하는 능력이 뛰어나고 벤젠, 포름알데히드등의 화학물질을 제거하는데 좋아 공기정화식물로도 좋아요. 물을 충분한 주는 것이 중요해요.",
        "toxctyInfo": "",
        "frtlzrInfo": "비료_종종_주세요",
        "postngplaceCodeNm": "약간 어두운 곳"
    }
]

export default DATA;